use_frameworks!

platform :ios, '8.0'

target 'TRULogining_Example' do
  pod 'TRULogining', :path => '../'
  pod 'TRUNetworking'

  target 'TRULogining_Tests' do
    inherit! :search_paths

    
  end
end
